Update Mock
Maua-Dev/mf_mss_product pull request #11
Opened 2023-03-02 02:41 UTC by LucasKiller

Fixing and updating enums and previous tests

2023-03-02 23:13 UTC, JoaoVitorBranco requested changes

2023-03-02 23:13 UTC, JoaoVitorBranco commented on src/shared/infra/repositories/product_repository_mock.py
> +            Product(available=True, price=32.0, name='Omelete de Presunto', description='Este prato inclui 2 acompanhamentos:\nArroz Feijão, Arroz a Grega, Arroz Integral, Creme de Milho, Mix Legumes
junta os 3 omeletes em uma entidade só. Se a gnt tiver q atualizar o preço deles, vamos ter q atualizar de 3 entidades de uma vez, e pode dar merda. Coloca no nome: Omelete( Queijo, Presunto e Tomate)

2023-03-02 23:36 UTC, RodrigoM2004 commented on src/shared/infra/repositories/product_repository_mock.py
> +            Product(available=True, price=32.0, name='Omelete de Presunto', description='Este prato inclui 2 acompanhamentos:\nArroz Feijão, Arroz a Grega, Arroz Integral, Creme de Milho, Mix Legumes
feito

2023-03-03 00:00 UTC, JoaoVitorBranco approved these changes

2023-03-03 00:00 UTC, merged