Merge branch create_schedule_tu_mock -> dev
Maua-Dev/mf_mss_product pull request #112
Opened 2024-10-07 21:58 UTC by Pistori1

O trabalho arduo de 3 jovens aprendizes

2024-10-08 15:15 UTC, RodrigoM2004 requested changes

2024-10-08 15:15 UTC, RodrigoM2004 commented on src/modules/create_schedule/app/create_schedule_controller.py
todas essas verificacoes da linha 43 até 54 podem ser apagadas, pq setamos no usecase que o restaurante vem do usuario e la verificamos se o usuario possui um restaurante, bem como o booleano accepted reservation que é setado no usecase para True sempre que um novo schedule for criado

2024-10-08 15:15 UTC, RodrigoM2004 commented on src/modules/get_all_schedules_by_restaurant/app/get_all_schedules_by_restaurant_viewmodel.py
enzao, pode parecer besteira, mas so renomeia a classe de GetAllSchedulesViewmodel para GetAllSchedulesByRestaurantViewmodel

2024-10-08 15:15 UTC, RodrigoM2004 commented on src/modules/get_schedule_by_id/app/get_schedule_by_id_usecase.py
realmente gus, pensei melhor aqui, nao tem necessidade dessa verificacao de user.restaurant e nem da condicao seguinte de if user.role == ADMIN, então pode apagar da linha 27 a 31

2024-10-08 15:15 UTC, RodrigoM2004 commented on src/modules/get_schedule_by_id/app/get_schedule_by_id_usecase.py
só uma outra coisinha, rearranja as verificacoes da seguinte forma: da o get user, coloca em sequencia a verificacao se o usuario é registrado, e depois da o get schedule e verifica se o schedule existe, fechou? pq dessa forma sempre que a gnt busca alguma coisa no banco, a gnt ja realiza a verificacao pra levantar ou nao o erro, e so ai nesse caso de nao levantar o erro, buscamos alguma outra coisa que precise

2024-10-10 22:39 UTC, Pistori1 commented on src/modules/get_all_schedules_by_restaurant/app/get_all_schedules_by_restaurant_viewmodel.py
Pronto

2024-10-11 18:21 UTC, RodrigoM2004 approved these changes

2024-10-11 18:25 UTC, merged