Update repository mock Sousa de Abreu 🥱
Maua-Dev/mf_mss_product pull request #14
Opened 2023-03-07 22:48 UTC by LucasKiller

2023-03-07 23:42 UTC, JoaoVitorBranco requested changes

2023-03-07 23:42 UTC, JoaoVitorBranco commented on src/shared/infra/repositories/product_repository_mock.py
> +            Product(available=True, price=29.0, name='Omelete c/ Salada', description='Ovo/Alface/Tomate/No Prato', prepare_time=20, meal_type=MEAL_TYPE.SALADS, photo='https://avatars.githubuserconte
plate

2023-03-08 03:36 UTC, LucasKiller commented on src/shared/infra/repositories/product_repository_mock.py
> +            Product(available=True, price=29.0, name='Omelete c/ Salada', description='Ovo/Alface/Tomate/No Prato', prepare_time=20, meal_type=MEAL_TYPE.SALADS, photo='https://avatars.githubuserconte
ok

2023-03-08 23:09 UTC, JoaoVitorBranco approved these changes

2023-03-08 23:09 UTC, merged