Get product
Maua-Dev/mf_mss_product pull request #15
Opened 2023-03-12 18:03 UTC by RodrigoM2004

2023-03-12 21:14 UTC, JoaoVitorBranco requested changes

2023-03-12 21:14 UTC, JoaoVitorBranco commented on src/shared/infra/repositories/product_repository_mock.py
> +        return None
commit p/ "Mock with tu", além de fazer tu do mock

2023-03-12 21:14 UTC, JoaoVitorBranco commented on src/modules/get_product/app/get_product_usecase.py
> +
usar "validade_product_id" para validar o ID, adicionando um teste de usecase para validar isso

2023-03-12 21:14 UTC, JoaoVitorBranco commented on tests/modules/get_product/app/test_get_product_usecase.py
> +    def test_get_product_usecase_with_invalid_product_id(self):
invalid_type ou not_str

2023-03-12 21:14 UTC, JoaoVitorBranco commented on src/modules/get_product/app/get_product_controller.py
> +        except NoItemsFound as err:
Eu vi q c fez isso por conta da tradução feita na SMILE. Mas, como não foi discutido isso no MF, queria q os erros fossem em inglês. Além disso, os outros erros das outras rotas estão em inglês, então seria meme fz 1 rota com erros em pt e outras em Inglês. Futuramente, se pedirem pra refatorar isso, a gnt faz de uma vez.

2023-03-12 21:14 UTC, JoaoVitorBranco commented on tests/modules/get_product/app/test_get_product_controller.py
> +
testa o NoItemsFound tbm

2023-03-12 21:14 UTC, JoaoVitorBranco commented on tests/modules/get_product/app/test_get_product_presenter.py
> +
testa um 404 (NoItemsFound)

2023-03-13 00:13 UTC, RodrigoM2004 commented on tests/modules/get_product/app/test_get_product_usecase.py
> +    def test_get_product_usecase_with_invalid_product_id(self):
feito

2023-03-13 00:17 UTC, RodrigoM2004 commented on src/shared/infra/repositories/product_repository_mock.py
> +        return None
feito

2023-03-13 00:21 UTC, RodrigoM2004 commented on src/modules/get_product/app/get_product_usecase.py
> +
feito

2023-03-13 00:26 UTC, RodrigoM2004 commented on src/modules/get_product/app/get_product_controller.py
> +        except NoItemsFound as err:
feito

2023-03-13 01:26 UTC, RodrigoM2004 commented on tests/modules/get_product/app/test_get_product_controller.py
> +
feito

2023-03-13 01:26 UTC, RodrigoM2004 commented on tests/modules/get_product/app/test_get_product_presenter.py
> +
feito

2023-03-13 18:21 UTC, JoaoVitorBranco requested changes

2023-03-13 18:21 UTC, JoaoVitorBranco commented on src/modules/get_product/app/get_product_controller.py
> +            message = err.message
return NotFound(body="Product not found")

2023-03-13 18:21 UTC, JoaoVitorBranco commented on src/modules/get_product/app/get_product_controller.py
> +            message = err.message
n precisa do resto

2023-03-13 18:26 UTC, JoaoVitorBranco approved these changes

2023-03-13 18:27 UTC, merged