Update product
Maua-Dev/mf_mss_product pull request #16
Opened 2023-03-14 02:09 UTC by LucasKiller

2023-03-14 02:39 UTC, JoaoVitorBranco requested changes

2023-03-14 02:39 UTC, JoaoVitorBranco commented on src/shared/infra/repositories/product_repository_mock.py
> +    def update_product(self, product_id: str, restaurant: RESTAURANT, new_available: bool = None, new_price: float = None, new_name: str = None, new_description: str = None, new_prepare_time: int = N
faltou teste do mock

2023-03-14 02:39 UTC, JoaoVitorBranco commented on src/modules/update_product/app/update_product_presenter.py
> +from src.modules.update_product.app.update_product_controller import UpdateProductController
Importa certo

2023-03-14 02:39 UTC, JoaoVitorBranco commented on src/modules/update_product/app/update_product_controller.py
> +from src.modules.update_product.app.update_product_usecase import UpdateProductUsecase
Importa certo

2023-03-14 02:39 UTC, JoaoVitorBranco commented on src/modules/update_product/app/update_product_controller.py
> +                new_last_update=int(request.data.get("new_last_update"))
new_last_update = datetime.datetime.now() (transforma pra formatação certa). Como vc ta dando update, o new_last_update vai ser nessa requisição!

2023-03-14 02:39 UTC, JoaoVitorBranco commented on tests/modules/update_product/app/test_update_product_usecase.py
> +
na próxima faz na ordem pra facilita minha vida

2023-03-14 02:39 UTC, JoaoVitorBranco commented on src/modules/update_product/app/update_product_controller.py
> +                )
new_last_update, então, não vai ser pego da request do controller

2023-03-14 02:39 UTC, JoaoVitorBranco commented on tests/modules/update_product/app/test_update_product_presenter.py
> +                },
testa um 404

2023-03-14 02:39 UTC, JoaoVitorBranco commented on tests/modules/update_product/app/test_update_product_presenter.py
> +        assert response["statusCode"] == 200
valida alguma coisa do conteúdo do body para garantir q tá certin

2023-03-15 01:57 UTC, LucasKiller commented on src/shared/infra/repositories/product_repository_mock.py
> +    def update_product(self, product_id: str, restaurant: RESTAURANT, new_available: bool = None, new_price: float = None, new_name: str = None, new_description: str = None, new_prepare_time: int = N
ok

2023-03-15 01:57 UTC, LucasKiller commented on src/modules/update_product/app/update_product_presenter.py
> +from src.modules.update_product.app.update_product_controller import UpdateProductController
ok

2023-03-15 01:57 UTC, LucasKiller commented on src/modules/update_product/app/update_product_controller.py
> +from src.modules.update_product.app.update_product_usecase import UpdateProductUsecase
ok

2023-03-15 01:57 UTC, LucasKiller commented on src/modules/update_product/app/update_product_controller.py
> +                new_last_update=int(request.data.get("new_last_update"))
ok

2023-03-15 01:59 UTC, LucasKiller commented on tests/modules/update_product/app/test_update_product_usecase.py
> +
certo kkkk

2023-03-15 01:59 UTC, LucasKiller commented on src/modules/update_product/app/update_product_controller.py
> +                )
ok

2023-03-15 02:21 UTC, LucasKiller commented on tests/modules/update_product/app/test_update_product_presenter.py
> +        assert response["statusCode"] == 200
ok

2023-03-15 02:50 UTC, LucasKiller commented on tests/modules/update_product/app/test_update_product_presenter.py
> +                },
ok

2023-03-18 21:23 UTC, JoaoVitorBranco approved these changes

2023-03-18 21:23 UTC, merged