DTO route 😎
Maua-Dev/mf_mss_product pull request #17
Opened 2023-03-19 15:55 UTC by LucasKiller

2023-03-21 22:52 UTC, JoaoVitorBranco requested changes
talk about them

2023-03-21 22:52 UTC, JoaoVitorBranco commented on tests/shared/infra/dto/test_product_dynamo_dto.py
> +            "price": repo.products[0].price,
coloca Decimal

2023-03-21 22:52 UTC, JoaoVitorBranco commented on tests/shared/infra/dto/test_product_dynamo_dto.py
> +            "price": repo.products[0].price,
valida o tipo

2023-03-21 22:52 UTC, JoaoVitorBranco commented on tests/shared/infra/dto/test_product_dynamo_dto.py
> +                                'prepare_time': '20',
Instanciar como Decimal aq e nos outros atributos Decimal

2023-03-22 00:39 UTC, LucasKiller commented on tests/shared/infra/dto/test_product_dynamo_dto.py
> +            "price": repo.products[0].price,
ok

2023-03-22 00:39 UTC, LucasKiller commented on tests/shared/infra/dto/test_product_dynamo_dto.py
> +                                'prepare_time': '20',
ok

2023-05-12 21:47 UTC, JoaoVitorBranco approved these changes

2023-05-12 21:47 UTC, JoaoVitorBranco commented on src/modules/get_product/app/get_product_usecase.py
>          if type(product_id) is not str:
pode tirar (validate já faz isso)

2023-05-12 21:47 UTC, JoaoVitorBranco commented on src/shared/infra/repositories/product_repository_dynamo.py
> +    def get_all_products_group_by_restaurant(self) -> Dict[RESTAURANT, List[Product]]:
seguir mesmo padrão da função do repo mock: se não encontrar items, retornar {} (o mock faz isso)

2023-05-12 21:47 UTC, JoaoVitorBranco commented on tests/shared/infra/repositories/test_product_repository_dynamo.py
> +    @pytest.mark.skip("Can't test dynamo in Github")
façam um teste de update de um item que vocês não encontram no bd (faz no mock tbm q n tem lá)

2023-05-12 21:47 UTC, JoaoVitorBranco commented on tests/shared/infra/repositories/test_product_repository_dynamo.py
> +    def test_get_product(self):
faz um get que não encontram o item

2023-05-12 21:47 UTC, JoaoVitorBranco commented on tests/shared/infra/repositories/test_product_repository_dynamo.py
> +    @pytest.mark.skip("Can't test dynamo in Github")
façam um delete que não encontram no repo (faz esse teste no mock tbm)

2023-05-12 21:48 UTC, JoaoVitorBranco requested changes

2023-05-12 21:48 UTC, JoaoVitorBranco commented on src/modules/get_product/app/get_product_usecase.py
>          if type(product_id) is not str:
.

2023-05-18 00:45 UTC, JoaoVitorBranco approved these changes

2023-05-18 00:46 UTC, merged