Update user
Maua-Dev/mf_mss_product pull request #38
Opened 2023-07-07 15:01 UTC by Lucasdvs10

2023-07-07 23:26 UTC, VgsStudio requested changes

2023-07-07 23:26 UTC, VgsStudio commented on src/modules/update_user/app/update_user_usecase.py
> +        if new_email is not None:
A gente vai dar só o update do NOME por agora, tira tudo do e-mail.

2023-07-07 23:26 UTC, VgsStudio commented on src/modules/update_user/app/update_user_usecase.py
> +                raise DuplicatedItem("user_name")
Não sei se esse erro faz sentido. Vc retorna ele se o nome anterior igual o nome de update

Faz sentido ser duplicated?

2023-07-07 23:26 UTC, VgsStudio commented on src/modules/update_user/app/update_user_viewmodel.py
> +            "restaurant": self.restaurant
Acho que tinha que pegar o value do enum

2023-07-07 23:26 UTC, VgsStudio commented on tests/modules/get_user/app/test_get_user_presenter.py
> +    def test_get_user_presenter(self):
Lol

2023-07-07 23:26 UTC, VgsStudio commented on src/modules/update_user/app/update_user_controller.py
> +                                new_name=requester_user.name,
Isso não faz sentido, vc tem que receber o nome novo, no body

Não usar o já anterior!

além disso tira tudo de e-mail

2023-07-10 13:36 UTC, Lucasdvs10 commented on tests/modules/get_user/app/test_get_user_presenter.py
> +    def test_get_user_presenter(self):
Ops :v

2023-07-10 13:39 UTC, Lucasdvs10 commented on src/modules/update_user/app/update_user_viewmodel.py
> +            "restaurant": self.restaurant
Ok

2023-07-10 13:58 UTC, Lucasdvs10 commented on src/modules/update_user/app/update_user_controller.py
> +                                new_name=requester_user.name,
Arrumado

2023-07-10 15:16 UTC, Lucasdvs10 commented on src/modules/update_user/app/update_user_usecase.py
> +        if new_email is not None:
OK

2023-07-10 15:29 UTC, VgsStudio approved these changes
LGTM

2023-07-10 15:29 UTC, merged