Adding autentication to update prod route
Maua-Dev/mf_mss_product pull request #43
Opened 2023-07-14 20:49 UTC by Lucasdvs10

2023-07-24 19:48 UTC, VgsStudio requested changes

2023-07-24 19:48 UTC, VgsStudio commented on src/modules/update_product/app/update_product_usecase.py
> +        user = self.repo_user.get_user_by_id(user_id)
e se esse user não estiver cadastrado na aplicação? vc vai tomar NONE, ai quando pegar o ROLE vai tomar erro

2023-07-24 19:48 UTC, VgsStudio commented on src/modules/update_product/app/update_product_usecase.py
> +        user = self.repo_user.get_user_by_id(user_id)
tem que adicionar no usecase, cria um UnregisteredUser ou levanta um NoItemsFound, e ve no controller tbm

2023-07-25 19:14 UTC, Lucasdvs10 commented on src/modules/update_product/app/update_product_usecase.py
> +        user = self.repo_user.get_user_by_id(user_id)
Prontin :)

2023-07-26 00:00 UTC, VgsStudio approved these changes
LGTM

2023-07-26 00:00 UTC, merged