Refat update product
Maua-Dev/mf_mss_product pull request #49
Opened 2023-07-28 13:24 UTC by Lucasdvs10

2023-07-28 15:13 UTC, VgsStudio requested changes

2023-07-28 15:13 UTC, VgsStudio commented on src/modules/update_product/app/update_product_usecase.py
> +                 new_prepare_time: Optional[int] = -1,
-1, por que não None?

Adorei o Optinal

2023-07-28 15:13 UTC, VgsStudio commented on tests/modules/update_product/app/test_update_product_usecase.py
> +                              new_meal_type=MEAL_TYPE.DRINKS,
por que esse teste da erro?

2023-07-28 15:13 UTC, VgsStudio commented on src/modules/update_product/app/update_product_controller.py
> +            new_prepare_time = -1     # Since prepare time can be none, I am dealing with it in a different way
hmmmm tá, bom

2023-07-28 15:13 UTC, VgsStudio commented on src/modules/update_product/app/update_product_controller.py
> +                new_description=str(new_description) if new_description is not None else None,
a descrição tambem tem esse problema não? de ser poder ser none e tals, não?

2023-07-28 15:13 UTC, VgsStudio commented on src/shared/helpers/functions/get_event_for_presenter_tests.py
> +from src.shared.infra.repositories.user_repository_mock import UserRepositoryMock
kkkkkkkkkk vc criou um arquivo separado? FODA

talvez só adicionar o lance de poder ter coisa no query parameteres

mas n sei se isso devia estar justo com o shared, não tem necessidade de subir isso na nossa infra, mas legal gostei

2023-07-28 15:15 UTC, VgsStudio commented on src/modules/update_product/app/update_product_usecase.py
> +                 new_prepare_time: Optional[int] = -1,
(vi depois)

2023-07-28 16:47 UTC, Lucasdvs10 commented on tests/modules/update_product/app/test_update_product_usecase.py
> +                              new_meal_type=MEAL_TYPE.DRINKS,
Esse teste dá erro pq o id da foto deveria ser uma string e a gente tá passando um inteiro

2023-07-28 16:48 UTC, Lucasdvs10 commented on src/modules/update_product/app/update_product_controller.py
> +                new_description=str(new_description) if new_description is not None else None,
Não que eu saiba uaosdhsad

2023-07-28 16:51 UTC, Lucasdvs10 commented on src/shared/helpers/functions/get_event_for_presenter_tests.py
> +from src.shared.infra.repositories.user_repository_mock import UserRepositoryMock
Já que é um bagulho só pra teste, eu posso colocar no helpers da pasta tests.

Aí não sobe pro infra e tals

2023-07-28 17:33 UTC, Lucasdvs10 commented on src/modules/update_product/app/update_product_controller.py
> +                new_description=str(new_description) if new_description is not None else None,
Sim, a descrição tem esse lance tbm.
Já arrumei lá

2023-07-29 14:45 UTC, VgsStudio approved these changes
LGTM

2023-07-29 14:45 UTC, merged