Change order status route
Maua-Dev/mf_mss_product pull request #68
Opened 2023-08-31 22:56 UTC by Lucasdvs10

2023-09-01 19:51 UTC, VgsStudio requested changes

2023-09-01 19:51 UTC, VgsStudio commented on src/modules/change_order_status/app/change_order_status_controller.py
> +from src.modules.change_order_status.app.change_order_status_usecase import ChangeOrderStatusUsecase
import

2023-09-01 19:51 UTC, VgsStudio commented on src/shared/domain/entities/order.py
> +        self.last_status_update_milliseconds = self.creation_time_milliseconds
faltou validar o last_status tbm

2023-09-01 19:51 UTC, VgsStudio commented on src/shared/infra/repositories/order_repository_mock.py
> +            Order(order_id="b3f6c5aa-80ad-4f95-ae16-455b4f87fb53", user_name=users_repo[4].name,
coloca alguns que já foram atualizados com o last update

2023-09-01 19:51 UTC, VgsStudio commented on src/shared/infra/repositories/order_repository_mock.py
> +            Order(order_id="b3f6c5aa-80ad-4f95-ae16-455b4f87fb53", user_name=users_repo[4].name,
(alguns que estão em peding sei la)

2023-09-01 19:51 UTC, VgsStudio commented on src/modules/change_order_status/app/change_order_status_presenter.py
> +repo_product = Environments.get_product_repo()()
não precisa do repo product

2023-09-01 19:51 UTC, VgsStudio commented on src/modules/change_order_status/app/change_order_status_usecase.py
> +            raise ForbiddenAction("order")
cria um error específico

2023-09-01 19:51 UTC, VgsStudio commented on src/modules/change_order_status/app/change_order_status_usecase.py
> +        updated_order.last_status_update_milliseconds = int(datetime.now().timestamp() * 1000)
vc tem que atualizar o last status update no repo tbm, caso contrário não vai salvar que mudou o status :C

2023-09-01 19:51 UTC, VgsStudio commented on src/modules/change_order_status/app/change_order_status_viewmodel.py
> +        return {
falta o last_update aqui tbm (verifica os outros viewmodels)

2023-09-04 11:59 UTC, Lucasdvs10 commented on src/modules/change_order_status/app/change_order_status_controller.py
> +from src.modules.change_order_status.app.change_order_status_usecase import ChangeOrderStatusUsecase
OK

2023-09-04 12:23 UTC, Lucasdvs10 commented on src/shared/domain/entities/order.py
> +        self.last_status_update_milliseconds = self.creation_time_milliseconds
OK

2023-09-04 12:25 UTC, Lucasdvs10 commented on src/shared/infra/repositories/order_repository_mock.py
> +            Order(order_id="b3f6c5aa-80ad-4f95-ae16-455b4f87fb53", user_name=users_repo[4].name,
OK

2023-09-04 12:25 UTC, Lucasdvs10 commented on src/modules/change_order_status/app/change_order_status_presenter.py
> +repo_product = Environments.get_product_repo()()
OK

2023-09-04 12:29 UTC, Lucasdvs10 commented on src/modules/change_order_status/app/change_order_status_usecase.py
> +            raise ForbiddenAction("order")
Prontin

2023-09-04 12:29 UTC, Lucasdvs10 commented on src/modules/change_order_status/app/change_order_status_usecase.py
> +        updated_order.last_status_update_milliseconds = int(datetime.now().timestamp() * 1000)
OK

2023-09-04 12:30 UTC, Lucasdvs10 commented on src/modules/change_order_status/app/change_order_status_viewmodel.py
> +        return {
Prontin

2023-09-04 16:51 UTC, VgsStudio requested changes
nunca decepciona, Dudu!

2023-09-04 16:51 UTC, VgsStudio commented on src/shared/infra/repositories/order_repository_mock.py
> +                                 quantity=2)], creation_time_milliseconds=1692061296,
essas dastas não estou em milisegundos..........

2023-09-04 16:51 UTC, VgsStudio commented on src/shared/infra/repositories/order_repository_mock.py
> +                  last_status_update_milliseconds=1692061596),
deu update antes de aceitar? kkkkkkkkkkk

2023-09-04 16:51 UTC, VgsStudio commented on src/shared/infra/repositories/order_repository_mock.py
> +                  last_status_update_milliseconds=1692061596),
update antes de aceitar

2023-09-04 16:51 UTC, VgsStudio commented on src/shared/infra/repositories/order_repository_mock.py
> +                  last_status_update_milliseconds=1692061596),
olha todos ai  <3

2023-09-04 18:24 UTC, Lucasdvs10 commented on src/shared/infra/repositories/order_repository_mock.py
> +                                 quantity=2)], creation_time_milliseconds=1692061296,
Multipliquei todas as datas por 1000

2023-09-04 18:24 UTC, Lucasdvs10 commented on src/shared/infra/repositories/order_repository_mock.py
> +                  last_status_update_milliseconds=1692061596),
Ops :v

2023-09-04 18:25 UTC, Lucasdvs10 commented on src/shared/infra/repositories/order_repository_mock.py
> +                  last_status_update_milliseconds=1692061596),
Prontin. Agr se vc tentar instanciar um Order com last update menor que o creation time, vai tomar uma exceção na cara

2023-09-04 19:42 UTC, merged