Dto order
Maua-Dev/mf_mss_product pull request #74
Opened 2023-09-06 12:24 UTC by RodrigoM2004

2023-09-06 19:22 UTC, VgsStudio requested changes

2023-09-06 19:22 UTC, VgsStudio commented on src/shared/infra/dto/order_dynamo_dto.py
> +            "last_status_update_milliseconds": Decimal(str(self.last_status_update_milliseconds)),
last status update pode ser None tbm

2023-09-06 19:22 UTC, VgsStudio commented on src/shared/infra/dto/order_dynamo_dto.py
> +            last_status_update_milliseconds=int(order_data["last_status_update_milliseconds"]),
pode ser none

2023-09-06 19:22 UTC, VgsStudio commented on src/shared/infra/dto/order_dynamo_dto.py
> +            observation=str(order_data.get("observation")) if order_data.get("observation") is not None else None,
nesses dois vc podia só dar o GET, não precisava do str()

2023-09-07 13:06 UTC, RodrigoM2004 commented on src/shared/infra/dto/order_dynamo_dto.py
> +            last_status_update_milliseconds=int(order_data["last_status_update_milliseconds"]),
feito

2023-09-07 13:06 UTC, RodrigoM2004 commented on src/shared/infra/dto/order_dynamo_dto.py
> +            "last_status_update_milliseconds": Decimal(str(self.last_status_update_milliseconds)),
feito

2023-09-07 13:06 UTC, RodrigoM2004 commented on src/shared/infra/dto/order_dynamo_dto.py
> +            observation=str(order_data.get("observation")) if order_data.get("observation") is not None else None,
feito

2023-09-07 15:18 UTC, VgsStudio approved these changes

2023-09-07 15:49 UTC, merged