Get current state route
Maua-Dev/mf_mss_product pull request #78
Opened 2023-09-11 21:58 UTC by Lucasdvs10

2023-09-11 23:14 UTC, VgsStudio requested changes

2023-09-11 23:14 UTC, VgsStudio commented on src/modules/get_current_order_state_by_id/app/get_current_order_state_by_id_controller.py
> +from src.modules.get_current_order_state_by_id.app.get_current_order_state_by_id_viewmodel import \
import

2023-09-11 23:14 UTC, VgsStudio commented on src/modules/get_current_order_state_by_id/app/get_current_order_state_by_id_presenter.py
> +from src.modules.get_current_order_state_by_id.app.get_current_order_state_by_id_usecase import \
import

2023-09-11 23:14 UTC, VgsStudio commented on src/modules/get_current_order_state_by_id/app/get_current_order_state_by_id_presenter.py
> +repo_product = Environments.get_product_repo()()
tira esse repo

2023-09-11 23:15 UTC, VgsStudio commented
adiciona no LAMBDA stack

2023-09-12 18:04 UTC, Lucasdvs10 commented on src/modules/get_current_order_state_by_id/app/get_current_order_state_by_id_controller.py
> +from src.modules.get_current_order_state_by_id.app.get_current_order_state_by_id_viewmodel import \
OK

2023-09-12 18:04 UTC, Lucasdvs10 commented on src/modules/get_current_order_state_by_id/app/get_current_order_state_by_id_presenter.py
> +from src.modules.get_current_order_state_by_id.app.get_current_order_state_by_id_usecase import \
OK

2023-09-12 18:05 UTC, Lucasdvs10 commented on src/modules/get_current_order_state_by_id/app/get_current_order_state_by_id_presenter.py
> +repo_product = Environments.get_product_repo()()
Ok

2023-09-12 18:23 UTC, merged