get_all_orders_by_restaurant
Maua-Dev/mf_mss_product pull request #81
Opened 2023-09-12 23:44 UTC by FelipeCarillo

Created route get_all_orders_by_restaurant, that will return a list of 20 orders (most recent to oldest one) with pagination.

2023-09-13 01:36 UTC, VgsStudio requested changes

2023-09-13 01:36 UTC, VgsStudio commented on src/shared/domain/repositories/order_repository_interface.py
> +    def get_all_orders_by_restaurant(self, restaurant: RESTAURANT, order_id: str) -> List[Order]:
esse order_id é o do start? se sim, melhora o nome da variável pra dar pra entender melhor e explica essa logica na interface

2023-09-13 01:36 UTC, VgsStudio commented on src/modules/get_all_orders_by_restaurant/app/get_all_orders_by_restaurant_usecase.py
> +        if user is None:
faz essa verificação antes do user, se o user não estiver cadastrado vc nem verifica se tem o order_id

2023-09-13 01:36 UTC, VgsStudio commented on src/modules/get_all_orders_by_restaurant/app/get_all_orders_by_restaurant_usecase.py
> +        order = self.repo_order.get_order_by_id(order_id) # can be None
esse if pega o order id da start key? 
faz sentido a gente verificar se ela existe? 
se sim, não vale mais a pena a gente ver se order_id não é nulo antes de fazer essa request? (economiar requets é SEMPRE bom)

2023-09-13 01:36 UTC, VgsStudio commented on src/modules/get_all_orders_by_restaurant/app/get_all_orders_by_restaurant_controller.py
> +                                                              order_id=request.data.get('order_id'))
isso ta bom, mas existe uma possibilidade da gente ter que fazer um refat quando implementarmos o método do Dynamo, vamos ver direitinho......

2023-09-13 01:36 UTC, VgsStudio commented on src/modules/get_all_orders_by_restaurant/app/get_all_orders_by_restaurant_usecase.py
> +        order = self.repo_order.get_order_by_id(order_id) # can be None
(acho legal sim pegar a Order, é interesssante ter ela, talvez não agora, mas pro futuro)

2023-09-13 01:36 UTC, VgsStudio commented on src/modules/get_all_orders_by_restaurant/app/get_all_orders_by_restaurant_usecase.py
> +        return self.repo_order.get_all_orders_by_restaurant(restaurant=user.restaurant, order_id=order_id)
assim como no get history do portal interno, o usecase tem que ser responsável por retornar o id da último pedido (o mais velho) pra fazer com que o fornt consiga loadar mais pedido

2023-09-13 01:36 UTC, VgsStudio commented on src/shared/infra/repositories/order_repository_mock.py
> +                    return restaurant_orders[order_id_position:order_id_position + 20]
aqui fica amount

2023-09-13 01:36 UTC, VgsStudio commented on src/shared/domain/repositories/order_repository_interface.py
> +    def get_all_orders_by_restaurant(self, restaurant: RESTAURANT, order_id: str) -> List[Order]:
define um "amount" que vai ser a quantidade de pedidos que serão loadados, acho talvez 10-20 um bom valor, deixa cravado no argumento da função isso, não no MOCK (explica na interface tambem)

2023-09-13 23:03 UTC, VgsStudio requested changes

2023-09-13 23:03 UTC, VgsStudio commented on src/shared/infra/repositories/order_repository_mock.py
> +                    return restaurant_orders[order_id_position:order_id_position + 20]
troca esse 20 por amount

2023-09-14 23:23 UTC, merged

2023-09-14 23:29 UTC, Lucasdvs10 reviewed
Parece certin