Change order
Maua-Dev/mf_mss_product pull request #87
Opened 2023-09-26 18:49 UTC by Lucasdvs10

2023-09-26 23:18 UTC, VgsStudio requested changes

2023-09-26 23:18 UTC, VgsStudio commented on src/modules/change_order_by_id/app/change_order_by_id_controller.py
> +                for product in products_list:
os produtos vão mudar mesmo né?
o que tem que aparecer é a lsita de ids, igual no create_order
da uma olhada lá no create order pra ver certinho, tem que ser no usecase
coloca um testes disso também!

2023-09-26 23:46 UTC, VgsStudio commented on src/modules/change_order_by_id/app/change_order_by_id_controller.py
> +                for product in products_list:
adiciona a rota no lambda stack também

2023-09-27 01:27 UTC, Lucasdvs10 commented on src/modules/change_order_by_id/app/change_order_by_id_controller.py
> +                for product in products_list:
Prontin

2023-09-27 18:37 UTC, VgsStudio approved these changes

2023-09-27 22:10 UTC, merged